# Generated by Django 2.2.3 on 2019-07-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190724_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apmnt_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
