# Generated by Django 2.2.3 on 2019-07-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190724_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apmnt_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
