# Generated by Django 2.2.3 on 2019-07-31 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190724_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
