# Generated by Django 2.2.3 on 2019-08-03 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
