# Generated by Django 2.2.3 on 2019-08-06 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usrhome.test


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usrhome', '0002_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(default=usrhome.test.generate_order_id, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
