# Generated by Django 2.2.3 on 2019-08-06 13:54

from django.db import migrations, models
import usrhome.test


class Migration(migrations.Migration):

    dependencies = [
        ('usrhome', '0003_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='order_id',
            field=models.CharField(default=usrhome.test.generate_order_id, editable=False, max_length=20),
        ),
    ]
