# Generated by Django 2.2.3 on 2019-08-10 15:07

from django.db import migrations, models
import usrhome.test


class Migration(migrations.Migration):

    dependencies = [
        ('usrhome', '0005_auto_20190810_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='paid_on2',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='order_id',
            field=models.CharField(default=usrhome.test.generate_order_id, editable=False, max_length=20),
        ),
    ]
