# Generated by Django 2.2.3 on 2019-08-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usrhome', '0006_auto_20190810_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='paid_on2',
            new_name='paid_on',
        ),
    ]
